import type { Partner } from "./types";

export const ALL_PARTNERS: Partner[] = [
  // Cruise - Popular
  { name: "Norwegian Cruise Line", short: "Norwegian", category: "popular" },
  { name: "Royal Caribbean", short: "Royal Caribbean", category: "popular" },
  { name: "Celebrity Cruises", short: "Celebrity", category: "popular" },
  { name: "Disney Cruise Line", short: "Disney Cruise Line", category: "popular" },
  { name: "Virgin Voyages", short: "Virgin Voyages", category: "popular" },
  { name: "Holland America Line", short: "Holland America", category: "popular" },
  { name: "Princess Cruises", short: "Princess", category: "popular" },
  { name: "Carnival Cruise Line", short: "Carnival", category: "popular" },
  { name: "MSC Cruises", short: "MSC", category: "popular" },
  // Cruise - Luxury/River
  { name: "Viking Ocean Cruises", short: "Viking Ocean", category: "luxury" },
  { name: "Viking River Cruises", short: "Viking River", category: "luxury" },
  { name: "Seabourn", short: "Seabourn", category: "luxury" },
  { name: "Regent Seven Seas Cruises", short: "Regent", category: "luxury" },
  { name: "Oceania Cruises", short: "Oceania", category: "luxury" },
  { name: "Silversea", short: "Silversea", category: "luxury" },
  { name: "Explora Journeys", short: "Explora", category: "luxury" },
  { name: "Azamara", short: "Azamara", category: "luxury" },
  { name: "AmaWaterways", short: "AmaWaterways", category: "luxury" },
  { name: "Avalon Waterways", short: "Avalon", category: "luxury" },
  { name: "Uniworld Boutique River Cruises", short: "Uniworld", category: "luxury" },
  { name: "Scenic River Cruises", short: "Scenic River", category: "luxury" },
  { name: "Scenic Eclipse", short: "Scenic Eclipse", category: "luxury" },
  { name: "Crystal Cruises", short: "Crystal", category: "luxury" },
  { name: "Cunard", short: "Cunard", category: "luxury" },
  { name: "Windstar Cruises", short: "Windstar", category: "luxury" },
  { name: "Paul Gauguin Cruises", short: "Paul Gauguin", category: "luxury" },
  { name: "Ponant", short: "Ponant", category: "luxury" },
  { name: "Ritz-Carlton Yacht Collection", short: "Ritz-Carlton Yacht", category: "luxury" },
  { name: "Four Seasons Yachts", short: "Four Seasons Yachts", category: "luxury" },
  // Expedition
  { name: "Lindblad Expeditions", short: "Lindblad", category: "expedition" },
  { name: "Hurtigruten", short: "Hurtigruten", category: "expedition" },
  { name: "UnCruise Adventures", short: "UnCruise", category: "expedition" },
  { name: "Atlas Ocean Voyages", short: "Atlas", category: "expedition" },
  // Tours
  { name: "Globus Journeys", short: "Globus", category: "tour" },
  { name: "Trafalgar", short: "Trafalgar", category: "tour" },
  { name: "Collette", short: "Collette", category: "tour" },
  { name: "CIE Tours", short: "CIE Tours", category: "tour" },
  { name: "G Adventures", short: "G Adventures", category: "tour" },
  { name: "Abercrombie & Kent", short: "A&K", category: "tour" },
  { name: "Tauck Cruises", short: "Tauck", category: "tour" },
  { name: "Rocky Mountaineer", short: "Rocky Mountaineer", category: "tour" },
  // Disney
  { name: "DisneyWorld", short: "DisneyWorld", category: "disney" },
  { name: "Disneyland", short: "Disneyland", category: "disney" },
  { name: "Aulani", short: "Aulani", category: "disney" },
  { name: "Adventures by Disney", short: "Adventures by Disney", category: "disney" },
  // Resorts
  { name: "Sandals", short: "Sandals", category: "resort" },
  { name: "Beaches Resorts", short: "Beaches", category: "resort" },
  { name: "Club Med", short: "Club Med", category: "resort" },
  { name: "Atlantis Paradise Island", short: "Atlantis", category: "resort" },
  { name: "Hard Rock Hotels", short: "Hard Rock", category: "resort" },
  { name: "Excellence Resorts", short: "Excellence", category: "resort" },
  { name: "Secrets Resorts", short: "Secrets", category: "resort" },
  { name: "Dreams Resorts", short: "Dreams", category: "resort" },
  { name: "Breathless Resorts", short: "Breathless", category: "resort" },
  { name: "Palace Resorts", short: "Palace", category: "resort" },
  { name: "RIU Hotels & Resorts", short: "RIU", category: "resort" },
  { name: "Iberostar Hotels & Resorts", short: "Iberostar", category: "resort" },
  // Vacations
  { name: "Delta Vacations", short: "Delta Vacations", category: "vacation" },
  { name: "American Airlines Vacations", short: "AA Vacations", category: "vacation" },
  { name: "United Vacations", short: "United Vacations", category: "vacation" },
  { name: "Southwest Vacations", short: "Southwest Vacations", category: "vacation" },
].sort((a, b) => a.short.localeCompare(b.short));

export const PRIORITY_TIERS = [
  ["Norwegian Cruise Line", "Royal Caribbean"],
  ["Celebrity Cruises", "Disney Cruise Line", "Virgin Voyages", "Holland America Line", "Princess Cruises"],
  ["Carnival Cruise Line", "MSC Cruises"]
];

export const SUPPLIER_ALIASES: Record<string, string> = {
  "ama waterways": "AmaWaterways", "amawaterways": "AmaWaterways",
  "disney cruises": "Disney Cruise Line", "viking cruises": "Viking Ocean Cruises",
  "viking ocean & expedition": "Viking Ocean Cruises", "windstar": "Windstar Cruises",
  "norwegian cruise line": "Norwegian Cruise Line", "royal caribbean": "Royal Caribbean",
  "celebrity cruises": "Celebrity Cruises", "disney cruise line": "Disney Cruise Line",
  "virgin voyages": "Virgin Voyages", "holland america line": "Holland America Line",
  "princess": "Princess Cruises", "princess cruises": "Princess Cruises",
  "carnival": "Carnival Cruise Line", "carnival cruise line": "Carnival Cruise Line",
  "msc cruises": "MSC Cruises", "viking": "Viking Ocean Cruises",
  "viking ocean cruises": "Viking Ocean Cruises", "seabourn": "Seabourn",
  "regent seven seas cruises": "Regent Seven Seas Cruises", "oceania cruises": "Oceania Cruises",
  "silversea": "Silversea", "explora journeys": "Explora Journeys", "azamara": "Azamara",
  "avalon waterways": "Avalon Waterways", "uniworld": "Uniworld Boutique River Cruises",
  "uniworld boutique river cruises": "Uniworld Boutique River Cruises",
  "scenic river": "Scenic River Cruises", "scenic luxury cruises & tours": "Scenic River Cruises",
  "scenic river cruises": "Scenic River Cruises", "scenic eclipse": "Scenic Eclipse",
  "scenic eclipse ocean voyages": "Scenic Eclipse", "crystal cruises": "Crystal Cruises",
  "cunard": "Cunard", "windstar cruises": "Windstar Cruises",
  "paul gauguin cruises": "Paul Gauguin Cruises", "ponant": "Ponant",
  "ritz-carlton yacht collection": "Ritz-Carlton Yacht Collection",
  "four seasons yachts": "Four Seasons Yachts", "lindblad expeditions": "Lindblad Expeditions",
  "lindblad expeditions & national geographic": "Lindblad Expeditions",
  "hurtigruten": "Hurtigruten", "uncruise adventures": "UnCruise Adventures",
  "atlas ocean voyages": "Atlas Ocean Voyages", "globus journeys": "Globus Journeys",
  "globus": "Globus Journeys", "trafalgar": "Trafalgar", "collette": "Collette",
  "cie tours": "CIE Tours", "g adventures": "G Adventures",
  "abercrombie & kent": "Abercrombie & Kent", "tauck cruises": "Tauck Cruises",
  "rocky mountaineer": "Rocky Mountaineer", "disneyworld": "DisneyWorld",
  "walt disney world": "DisneyWorld", "disneyland": "Disneyland",
  "aulani a disney resort & spa": "Aulani", "aulani": "Aulani",
  "adventures by disney": "Adventures by Disney", "sandals": "Sandals",
  "beaches": "Beaches Resorts", "beaches resorts": "Beaches Resorts",
  "club med": "Club Med", "atlantis paradise island": "Atlantis Paradise Island",
  "atlantis paradise island bahamas": "Atlantis Paradise Island", "atlantis": "Atlantis Paradise Island",
  "hard rock hotels": "Hard Rock Hotels", "hard rock hotel & casino": "Hard Rock Hotels",
  "excellence resorts": "Excellence Resorts", "secrets": "Secrets Resorts",
  "secrets resorts": "Secrets Resorts", "dreams": "Dreams Resorts",
  "dreams resorts": "Dreams Resorts", "breathless": "Breathless Resorts",
  "breathless resorts": "Breathless Resorts", "palace resorts": "Palace Resorts",
  "riu hotels & resorts": "RIU Hotels & Resorts", "iberostar hotels & resorts": "Iberostar Hotels & Resorts",
  "iberostar beachfront resorts": "Iberostar Hotels & Resorts",
  "delta vacations": "Delta Vacations", "american airlines vacations": "American Airlines Vacations",
  "american airline vacations": "American Airlines Vacations",
  "united vacations": "United Vacations", "southwest vacations": "Southwest Vacations",
  "viking river cruises": "Viking River Cruises"
};