# This file defines the CI/CD pipeline for the "Living Canvas" project.

stages:
  - test
  - quality_scan

.python_template:
  image: python:3.11-slim
  before_script:
    - pip install pytest radon sonarqube-scanner

test_suite:
  stage: test
  extends: .python_template
  script:
    - pytest --junitxml=report.xml
  artifacts:
    reports:
      junit: report.xml

radon_complexity_check:
  stage: quality_scan
  extends: .python_template
  script:
    # Fails the job if any function's cyclomatic complexity > 15
    - radon cc . --max-complexity 15

sonar_quality_gate:
  stage: quality_scan
  extends: .python_template
  variables:
    GIT_DEPTH: "0"
  script:
    # Fails the job if the SonarQube Quality Gate is not met.
    - >
      sonar-scanner
      -Dsonar.projectKey=living-canvas
      -Dsonar.sources=.
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.qualitygate.wait=true
